# Generated by Django 3.2.16 on 2023-04-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf_data_processing', '0002_historicaltaxfiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxfiling',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to=settings.AUTH_USER_MODEL),
        ),
    ]
